'use strict';
var e,g="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},k="object"===typeof g.global&&g.global?g.global:"object"===typeof global&&global&&global.Object===Object?global:this;g.global=k;var aa=exports;g.exportsNamespace=aa;k.Object.freeze(g);var ba={envInfo:g,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.27",globalThis:this};k.Object.freeze(ba);k.Object.freeze(ba.semantics);
var m=k.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=k.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=k.WeakMap?new k.WeakMap:null;function p(a){return function(b,c){return!(!b||!b.$classData||b.$classData.v!==c||b.$classData.t!==a)}}
function fa(a){for(var b in a)return b}function ga(a,b,c){var d=new a.U(b[c]);if(c<b.length-1){a=a.x;c+=1;for(var f=d.S,h=0;h<f.length;h++)f[h]=ga(a,b,c)}return d}function ha(a){return void 0===a?"undefined":a.toString()}
function ia(a){switch(typeof a){case "string":return q(ja);case "number":var b=a|0;return b===a?ka(b)?q(la):ma(b)?q(na):q(oa):"number"===typeof a?q(pa):q(qa);case "boolean":return q(ra);case "undefined":return q(sa);default:return null===a?a.Wa():ta(a)?q(ua):a&&a.$classData?q(a.$classData):null}}
function va(a){switch(typeof a){case "string":return r(t(),a);case "number":return wa(xa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.y():null===ea?42:ya(a)}}function za(a,b){var c=k.Object.getPrototypeOf,d=k.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}function Aa(a,b,c){a=za(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Ba(a,b,c,d){a=za(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new k.TypeError("super has no setter '"+c+"'.");}
var ya=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return va(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(k.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:va(a)};function ka(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function ma(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function u(){this.K=this.U=void 0;this.t=this.x=this.e=null;this.v=0;this.T=null;this.E="";this.d=this.C=this.D=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function v(a,b,c){var d=new u;d.e={};d.x=null;d.T=a;d.E=b;d.d=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function x(a,b,c,d,f,h,n){var l=new u,w=fa(a);h=h||function(a){return!!(a&&a.$classData&&a.$classData.e[w])};n=n||function(a,b){return!!(a&&a.$classData&&a.$classData.v===b&&a.$classData.t.e[w])};l.K=f;l.e=c;l.E="L"+b+";";l.d=n;l.name=b;l.isInterface=!1;l.isRawJSType=!!d;l.isInstance=h;return l}
function Ca(a){function b(a){if("number"===typeof a){this.S=Array(a);for(var b=0;b<a;b++)this.S[b]=f}else this.S=a}var c=new u,d=a.T,f="longZero"==d?y().B:d;b.prototype=new z;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.E,h=a.t||a,n=a.v+1;c.U=b;c.K=Da;c.e={a:1,Za:1,c:1};c.x=a;c.t=h;c.v=n;c.T=null;c.E=d;c.D=void 0;c.C=void 0;c.d=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return h.d(a,n)};return c}
function q(a){if(!a.D){var b=new A;b.f=a;a.D=b}return a.D}u.prototype.getFakeInstance=function(){return this===ja?"some string":this===ra?!1:this===la||this===na||this===oa||this===pa||this===qa?0:this===ua?y().B:this===sa?void 0:{$classData:this}};u.prototype.getSuperclass=function(){return this.K?q(this.K):null};u.prototype.getComponentType=function(){return this.x?q(this.x):null};
u.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.C||(b.C=Ca(b)),b=b.C;return ga(b,a,0)};var Ea=v(!1,"Z","boolean"),Fa=v(0,"C","char"),Ga=v(0,"B","byte"),Ha=v(0,"S","short"),Ia=v(0,"I","int"),Ja=v("longZero","J","long"),Ka=v(0,"F","float"),La=v(0,"D","double");Ea.d=p(Ea);Fa.d=p(Fa);Ga.d=p(Ga);Ha.d=p(Ha);Ia.d=p(Ia);Ja.d=p(Ja);Ka.d=p(Ka);La.d=p(La);function B(){}function z(){}z.prototype=B.prototype;B.prototype.b=function(){return this};B.prototype.k=function(){var a=ia(this).f.name,b=(+(this.y()>>>0)).toString(16);return a+"@"+b};B.prototype.y=function(){return ya(this)};B.prototype.toString=function(){return this.k()};var Da=x({a:0},"java.lang.Object",{a:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.v||0;return!(c<b)&&(c>b||!a.t.isPrimitive)}return!1});B.prototype.$classData=Da;function C(){}
C.prototype=new z;C.prototype.constructor=C;C.prototype.b=function(){return this};C.prototype.$classData=x({ja:0},"HelloWorldApp$",{ja:1,a:1});var Ma=void 0;function D(){}D.prototype=new z;D.prototype.constructor=D;D.prototype.b=function(){return this};D.prototype.square=function(a){a|=0;return m(a,a)};D.prototype.$classData=x({ka:0},"HelloWorldLib$",{ka:1,a:1});var Na=void 0;function A(){this.f=null}A.prototype=new z;A.prototype.constructor=A;
A.prototype.k=function(){return(this.f.isInterface?"interface ":this.f.isPrimitive?"":"class ")+this.f.name};A.prototype.$classData=x({va:0},"java.lang.Class",{va:1,a:1});function E(){this.W=this.ca=null}E.prototype=new z;E.prototype.constructor=E;E.prototype.b=function(){Oa=this;this.ca=Pa(!1);this.W=Pa(!0);return this};E.prototype.$classData=x({Ea:0},"java.lang.System$",{Ea:1,a:1});var Oa=void 0;function Qa(){Oa||(Oa=(new E).b());return Oa}function Ra(){}Ra.prototype=new z;
Ra.prototype.constructor=Ra;function Sa(){}Sa.prototype=Ra.prototype;function F(){this.q=null}F.prototype=new z;F.prototype.constructor=F;F.prototype.k=function(){return"DynamicVariable("+this.q+")"};F.prototype.i=function(a){this.q=a;return this};F.prototype.$classData=x({Ka:0},"scala.util.DynamicVariable",{Ka:1,a:1});function Ta(){}Ta.prototype=new z;Ta.prototype.constructor=Ta;function Ua(){}Ua.prototype=Ta.prototype;
function Va(a){Wa||(Wa=(new G).b());var b=a.da();if(0===b)return a=a.fa(),r(t(),a);for(var c=-889275714,d=0;d<b;){Xa||(Xa=(new H).b());var f=Za(a.ea(d)),f=m(-862048943,f),f=m(461845907,f<<15|f>>>17|0),c=c^f,c=-430675100+m(5,c<<13|c>>>19|0)|0,d=1+d|0}a=c^b;a=m(-2048144789,a^(a>>>16|0));a=m(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function I(){this.ha=null}I.prototype=new z;I.prototype.constructor=I;I.prototype.b=function(){$a=this;this.ha=k.Object.prototype.hasOwnProperty;return this};
I.prototype.$classData=x({Ma:0},"scala.scalajs.js.WrappedDictionary$Cache$",{Ma:1,a:1});var $a=void 0;function J(){this.j=!1;this.Y=this.H=this.u=null;this.M=!1;this.aa=this.Z=0}J.prototype=new z;J.prototype.constructor=J;
J.prototype.b=function(){ab=this;this.u=(this.j=!!(k.ArrayBuffer&&k.Int32Array&&k.Float32Array&&k.Float64Array))?new k.ArrayBuffer(8):null;this.H=this.j?new k.Int32Array(this.u,0,2):null;this.j&&new k.Float32Array(this.u,0,2);this.Y=this.j?new k.Float64Array(this.u,0,1):null;if(this.j)this.H[0]=16909060,a=1===((new k.Int8Array(this.u,0,8))[0]|0);else var a=!0;this.Z=(this.M=a)?0:1;this.aa=this.M?1:0;return this};
function wa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.j)a.Y[0]=b,a=bb(a.H[a.aa]|0,a.H[a.Z]|0);else{if(b!==b)a=!1,b=2047,c=+k.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+k.Math.pow(2,-1022)){b=+k.Math.pow(2,52);var c=+k.Math.log(d)/.6931471805599453,c=+k.Math.floor(c)|0,c=1023>c?c:1023,f=+k.Math.pow(2,c);f>d&&(c=-1+c|0,f/=2);f=d/f*b;d=+k.Math.floor(f);f-=d;d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/
b&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+k.Math.pow(2,-1074),c=+k.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=bb(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.p^a.m}J.prototype.$classData=x({Oa:0},"scala.scalajs.runtime.Bits$",{Oa:1,a:1});var ab=void 0;function xa(){ab||(ab=(new J).b());return ab}function K(){}K.prototype=new z;K.prototype.constructor=K;K.prototype.b=function(){return this};
function r(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+m(65535&(b.charCodeAt(d)|0),c)|0,c=m(31,c),d=-1+d|0;return a}K.prototype.$classData=x({Qa:0},"scala.scalajs.runtime.RuntimeString$",{Qa:1,a:1});var cb=void 0;function t(){cb||(cb=(new K).b());return cb}function L(){}L.prototype=new z;L.prototype.constructor=L;L.prototype.b=function(){return this};function db(a,b){return b&&b.$classData&&b.$classData.e.I?b:(new M).i(b)}
L.prototype.$classData=x({Ra:0},"scala.scalajs.runtime.package$",{Ra:1,a:1});var eb=void 0;function fb(){eb||(eb=(new L).b());return eb}function H(){}H.prototype=new z;H.prototype.constructor=H;H.prototype.b=function(){return this};
function Za(a){if(null===a)return 0;if("number"===typeof a){a=+a;var b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{var b=y(),c;if(-9223372036854775808>a)b.L=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.L=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.L=0>a&&0!==c?-1+d|0:d}b=b.L;y();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:wa(xa(),a)}return a}return ta(a)?(a=null===a?y().B:a,b=bb(a.p,a.m),a=b.p,b=b.m,b===a>>31?a:a^
b):va(a)}H.prototype.$classData=x({Ta:0},"scala.runtime.Statics$",{Ta:1,a:1});var Xa=void 0;function gb(){}gb.prototype=new z;gb.prototype.constructor=gb;function hb(){}hb.prototype=gb.prototype;function N(){this.h=null}N.prototype=new z;N.prototype.constructor=N;function ib(){}ib.prototype=N.prototype;
N.prototype.X=function(){if(void 0===k.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=db(fb(),b),null!==a)if(a&&a.$classData&&a.$classData.e.R)a=a.l;else throw fb(),a&&a.$classData&&a.$classData.e.R?a.l:a;else throw b;}this.stackdata=a}else k.Error.captureStackTrace(this),this.stackdata=this;return this};N.prototype.O=function(){return this.h};N.prototype.k=function(){var a=ia(this).f.name,b=this.O();return null===b?a:a+": "+b};N.prototype.G=function(a,b,c,d){this.h=a;d&&this.X();return this};
function G(){}G.prototype=new Ua;G.prototype.constructor=G;G.prototype.b=function(){Wa=this;r(t(),"Seq");r(t(),"Map");r(t(),"Set");return this};G.prototype.$classData=x({La:0},"scala.util.hashing.MurmurHash3$",{La:1,cb:1,a:1});var Wa=void 0,sa=x({Sa:0},"scala.runtime.BoxedUnit",{Sa:1,a:1,c:1},void 0,void 0,function(a){return void 0===a}),ra=x({ta:0},"java.lang.Boolean",{ta:1,a:1,c:1,g:1},void 0,void 0,function(a){return"boolean"===typeof a});function jb(){this.h=null}jb.prototype=new ib;
jb.prototype.constructor=jb;function kb(){}kb.prototype=jb.prototype;function O(){this.A=null}O.prototype=new Sa;O.prototype.constructor=O;O.prototype.b=function(){lb=this;this.A=(new F).i(Qa().ca);(new F).i(Qa().W);(new F).i(null);return this};O.prototype.$classData=x({Ga:0},"scala.Console$",{Ga:1,$a:1,a:1,bb:1});var lb=void 0;function mb(){lb||(lb=(new O).b());return lb}function P(){this.L=0;this.B=null}P.prototype=new z;P.prototype.constructor=P;
P.prototype.b=function(){nb=this;this.B=bb(0,0);return this};
function ob(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,h=a,n=b;for(a=b=0;0<=c&&0!==(-2097152&n);){var l=h,w=n,Ab=f,Ya=d;if(w===Ya?(-2147483648^l)>=(-2147483648^Ab):(-2147483648^w)>=(-2147483648^Ya))l=n,w=d,n=h-f|0,l=(-2147483648^n)>(-2147483648^h)?-1+(l-w|0)|0:l-w|0,h=n,n=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=d>>>1|0;f=f>>>1|0|d<<31;d=l}c=n;if(0===c?-1147483648<=(-2147483648^
h):-2147483648<=(-2147483648^c))c=4294967296*n+ +(h>>>0),h=c/1E9,f=h/4294967296|0,d=b,b=h=d+(h|0)|0,a=(-2147483648^h)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,h=c%1E9|0;c=""+h;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}P.prototype.$classData=x({Pa:0},"scala.scalajs.runtime.RuntimeLong$",{Pa:1,a:1,ga:1,c:1});var nb=void 0;function y(){nb||(nb=(new P).b());return nb}function pb(){}pb.prototype=new z;pb.prototype.constructor=pb;function qb(){}qb.prototype=pb.prototype;
var ja=x({oa:0},"java.lang.String",{oa:1,a:1,c:1,Ya:1,g:1},void 0,void 0,function(a){return"string"===typeof a}),la=x({ua:0},"java.lang.Byte",{ua:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return ka(a)}),qa=x({wa:0},"java.lang.Double",{wa:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),pa=x({xa:0},"java.lang.Float",{xa:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),oa=x({za:0},"java.lang.Integer",{za:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),ua=x({Ca:0},"java.lang.Long",{Ca:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return ta(a)});function rb(){this.h=null}rb.prototype=new kb;rb.prototype.constructor=rb;function Q(){}Q.prototype=rb.prototype;var na=x({Da:0},"java.lang.Short",{Da:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return ma(a)});function R(){this.J=this.V=null;this.n=0}R.prototype=new z;R.prototype.constructor=R;function sb(a){var b=new R;b.V=a;b.J=k.Object.keys(a);b.n=0;return b}
R.prototype.k=function(){return"\x3citerator\x3e"};function tb(a){var b=a.J[a.n];a.n=1+a.n|0;a=a.V;$a||($a=(new I).b());if($a.ha.call(a,b))a=a[b];else throw(new S).F("key not found: "+b);var c=new T;c.r=b;c.s=a;return c}R.prototype.$classData=x({Na:0},"scala.scalajs.js.WrappedDictionary$DictionaryIterator",{Na:1,a:1,eb:1,fb:1,db:1});function U(){this.m=this.p=0}U.prototype=new hb;U.prototype.constructor=U;
U.prototype.k=function(){y();var a=this.p,b=this.m;return b===a>>31?""+a:0>b?"-"+ob(-a|0,0!==a?~b:-b|0):ob(a,b)};function bb(a,b){var c=new U;c.p=a;c.m=b;return c}U.prototype.y=function(){return this.p^this.m};function ta(a){return!!(a&&a.$classData&&a.$classData.e.ia)}U.prototype.$classData=x({ia:0},"scala.scalajs.runtime.RuntimeLong",{ia:1,o:1,a:1,c:1,g:1});function V(){}V.prototype=new qb;V.prototype.constructor=V;function ub(){}ub.prototype=V.prototype;V.prototype.qa=function(){return this};
function W(){this.h=null}W.prototype=new Q;W.prototype.constructor=W;W.prototype.F=function(a){N.prototype.G.call(this,a,0,0,!0);return this};W.prototype.$classData=x({ya:0},"java.lang.IndexOutOfBoundsException",{ya:1,Q:1,P:1,I:1,a:1,c:1});function X(){}X.prototype=new qb;X.prototype.constructor=X;X.prototype.b=function(){return this};X.prototype.$classData=x({Ba:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Ba:1,na:1,a:1,la:1,sa:1,ma:1});function S(){this.h=null}S.prototype=new Q;
S.prototype.constructor=S;S.prototype.F=function(a){N.prototype.G.call(this,a,0,0,!0);return this};S.prototype.$classData=x({Fa:0},"java.util.NoSuchElementException",{Fa:1,Q:1,P:1,I:1,a:1,c:1});function Y(){this.z=this.ba=this.h=null;this.N=!1}Y.prototype=new Q;Y.prototype.constructor=Y;
Y.prototype.O=function(){if(!this.N&&!this.N){var a;if(null===this.z)a="null";else try{a=ha(this.z)+" ("+("of class "+ia(this.z).f.name)+")"}catch(b){if(null!==db(fb(),b))a="an instance of class "+ia(this.z).f.name;else throw b;}this.ba=a;this.N=!0}return this.ba};Y.prototype.i=function(a){this.z=a;N.prototype.G.call(this,null,0,0,!0);return this};Y.prototype.$classData=x({Ia:0},"scala.MatchError",{Ia:1,Q:1,P:1,I:1,a:1,c:1});function T(){this.s=this.r=null}T.prototype=new z;
T.prototype.constructor=T;e=T.prototype;e.fa=function(){return"Tuple2"};e.da=function(){return 2};e.ea=function(a){a:switch(a){case 0:a=this.r;break a;case 1:a=this.s;break a;default:throw(new W).F(""+a);}return a};e.k=function(){return"("+this.r+","+this.s+")"};e.y=function(){return Va(this)};e.$classData=x({pa:0},"scala.Tuple2",{pa:1,a:1,ab:1,Ja:1,Ha:1,ga:1,c:1});function Z(){}Z.prototype=new ub;Z.prototype.constructor=Z;function vb(){}vb.prototype=Z.prototype;
Z.prototype.ra=function(){V.prototype.qa.call(this);return this};function wb(){this.w=this.$=null}wb.prototype=new vb;wb.prototype.constructor=wb;function Pa(a){var b=new wb;b.$=a;(new X).b();Z.prototype.ra.call(b);b.w="";return b}function xb(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.w=""+a.w+b,b="";else{var d=""+a.w+b.substring(0,c);k.console&&(a.$&&k.console.error?k.console.error(d):k.console.log(d));a.w="";b=b.substring(1+c|0)}}}
wb.prototype.$classData=x({Aa:0},"java.lang.JSConsoleBasedPrintStream",{Aa:1,Va:1,Ua:1,na:1,a:1,la:1,sa:1,ma:1,Xa:1});function M(){this.l=this.h=null}M.prototype=new Q;M.prototype.constructor=M;e=M.prototype;e.fa=function(){return"JavaScriptException"};e.da=function(){return 1};e.X=function(){this.stackdata=this.l;return this};e.ea=function(a){switch(a){case 0:return this.l;default:throw(new W).F(""+a);}};e.O=function(){return ha(this.l)};
e.i=function(a){this.l=a;N.prototype.G.call(this,null,0,0,!0);return this};e.y=function(){return Va(this)};e.$classData=x({R:0},"scala.scalajs.js.JavaScriptException",{R:1,Q:1,P:1,I:1,a:1,c:1,Ja:1,Ha:1,ga:1});Na||(Na=(new D).b());aa.HelloWorldLib=Na;Ma||(Ma=(new C).b());xb(mb().A.q,"Hello world from Scala.js! dd\n");xb(mb().A.q,"----\n");xb(mb().A.q,"To demonstrate usage of Node.js api, here's some of your environment:\n");
for(var yb={},zb=0,Bb=sb(k.process.env);5>zb&&Bb.n<(Bb.J.length|0);){var Cb=tb(Bb);yb[Cb.r]=Cb.s;zb=1+zb|0}for(var Db=sb(yb);Db.n<(Db.J.length|0);){var Eb=tb(Db);if(null!==Eb){var Fb=Eb.r+" \x3d "+Eb.s;xb(mb().A.q,Fb+"\n")}else throw(new Y).i(Eb);};
//# sourceMappingURL=scalajs-cli-demo-opt.js.map
