'use strict';
var e,g="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},k="object"===typeof g.global&&g.global?g.global:"object"===typeof global&&global&&global.Object===Object?global:this;g.global=k;g.exportsNamespace=exports;k.Object.freeze(g);var aa={envInfo:g,semantics:{asInstanceOfs:2,arrayIndexOutOfBounds:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.27",globalThis:this};k.Object.freeze(aa);k.Object.freeze(aa.semantics);
var m=k.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ba=k.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},ca=0,da=k.WeakMap?new k.WeakMap:null;function p(a){return function(b,c){return!(!b||!b.$classData||b.$classData.v!==c||b.$classData.t!==a)}}
function ea(a){for(var b in a)return b}function fa(a,b,c){var d=new a.U(b[c]);if(c<b.length-1){a=a.x;c+=1;for(var f=d.S,h=0;h<f.length;h++)f[h]=fa(a,b,c)}return d}function ga(a){return void 0===a?"undefined":a.toString()}
function ha(a){switch(typeof a){case "string":return q(ia);case "number":var b=a|0;return b===a?ja(b)?q(ka):la(b)?q(ma):q(na):"number"===typeof a?q(oa):q(pa);case "boolean":return q(qa);case "undefined":return q(ra);default:return null===a?a.Va():sa(a)?q(ta):a&&a.$classData?q(a.$classData):null}}
function ua(a){switch(typeof a){case "string":return r(t(),a);case "number":return va(wa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.y():null===da?42:xa(a)}}function ya(a,b){var c=k.Object.getPrototypeOf,d=k.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var f=d(a,b);if(void 0!==f)return f;a=c(a)}}function za(a,b,c){a=ya(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Aa(a,b,c,d){a=ya(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new k.TypeError("super has no setter '"+c+"'.");}
var xa=null!==da?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ua(a);default:if(null===a)return 0;var b=da.get(a);void 0===b&&(ca=b=ca+1|0,da.set(a,b));return b}}:function(a){if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(k.Object.isSealed(a))return 42;ca=b=ca+1|0;return a.$idHashCode$0=b}return null===a?0:ua(a)};function ja(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}
function la(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0}function u(){this.K=this.U=void 0;this.t=this.x=this.e=null;this.v=0;this.T=null;this.E="";this.d=this.C=this.D=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function w(a,b,c){var d=new u;d.e={};d.x=null;d.T=a;d.E=b;d.d=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function x(a,b,c,d,f,h,n){var l=new u,v=ea(a);h=h||function(a){return!!(a&&a.$classData&&a.$classData.e[v])};n=n||function(a,b){return!!(a&&a.$classData&&a.$classData.v===b&&a.$classData.t.e[v])};l.K=f;l.e=c;l.E="L"+b+";";l.d=n;l.name=b;l.isInterface=!1;l.isRawJSType=!!d;l.isInstance=h;return l}
function Ba(a){function b(a){if("number"===typeof a){this.S=Array(a);for(var b=0;b<a;b++)this.S[b]=f}else this.S=a}var c=new u,d=a.T,f="longZero"==d?y().B:d;b.prototype=new z;b.prototype.constructor=b;b.prototype.$classData=c;var d="["+a.E,h=a.t||a,n=a.v+1;c.U=b;c.K=Ca;c.e={a:1,Ya:1,c:1};c.x=a;c.t=h;c.v=n;c.T=null;c.E=d;c.D=void 0;c.C=void 0;c.d=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return h.d(a,n)};return c}
function q(a){if(!a.D){var b=new A;b.f=a;a.D=b}return a.D}u.prototype.getFakeInstance=function(){return this===ia?"some string":this===qa?!1:this===ka||this===ma||this===na||this===oa||this===pa?0:this===ta?y().B:this===ra?void 0:{$classData:this}};u.prototype.getSuperclass=function(){return this.K?q(this.K):null};u.prototype.getComponentType=function(){return this.x?q(this.x):null};
u.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.C||(b.C=Ba(b)),b=b.C;return fa(b,a,0)};var Da=w(!1,"Z","boolean"),Ea=w(0,"C","char"),Fa=w(0,"B","byte"),Ga=w(0,"S","short"),Ha=w(0,"I","int"),Ia=w("longZero","J","long"),Ja=w(0,"F","float"),Ka=w(0,"D","double");Da.d=p(Da);Ea.d=p(Ea);Fa.d=p(Fa);Ga.d=p(Ga);Ha.d=p(Ha);Ia.d=p(Ia);Ja.d=p(Ja);Ka.d=p(Ka);function B(){}function z(){}z.prototype=B.prototype;B.prototype.b=function(){return this};B.prototype.k=function(){var a=ha(this).f.name,b=(+(this.y()>>>0)).toString(16);return a+"@"+b};B.prototype.y=function(){return xa(this)};B.prototype.toString=function(){return this.k()};var Ca=x({a:0},"java.lang.Object",{a:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var c=a.v||0;return!(c<b)&&(c>b||!a.t.isPrimitive)}return!1});B.prototype.$classData=Ca;function C(){}
C.prototype=new z;C.prototype.constructor=C;C.prototype.b=function(){return this};C.prototype.$classData=x({ja:0},"HelloWorldApp$",{ja:1,a:1});var La=void 0;function A(){this.f=null}A.prototype=new z;A.prototype.constructor=A;A.prototype.k=function(){return(this.f.isInterface?"interface ":this.f.isPrimitive?"":"class ")+this.f.name};A.prototype.$classData=x({ua:0},"java.lang.Class",{ua:1,a:1});function D(){this.W=this.ca=null}D.prototype=new z;D.prototype.constructor=D;
D.prototype.b=function(){Ma=this;this.ca=Na(!1);this.W=Na(!0);return this};D.prototype.$classData=x({Da:0},"java.lang.System$",{Da:1,a:1});var Ma=void 0;function Oa(){Ma||(Ma=(new D).b());return Ma}function Pa(){}Pa.prototype=new z;Pa.prototype.constructor=Pa;function Qa(){}Qa.prototype=Pa.prototype;function E(){this.q=null}E.prototype=new z;E.prototype.constructor=E;E.prototype.k=function(){return"DynamicVariable("+this.q+")"};E.prototype.i=function(a){this.q=a;return this};
E.prototype.$classData=x({Ja:0},"scala.util.DynamicVariable",{Ja:1,a:1});function Ra(){}Ra.prototype=new z;Ra.prototype.constructor=Ra;function Sa(){}Sa.prototype=Ra.prototype;
function Ta(a){Ua||(Ua=(new F).b());var b=a.da();if(0===b)return a=a.fa(),r(t(),a);for(var c=-889275714,d=0;d<b;){Wa||(Wa=(new G).b());var f=Xa(a.ea(d)),f=m(-862048943,f),f=m(461845907,f<<15|f>>>17|0),c=c^f,c=-430675100+m(5,c<<13|c>>>19|0)|0,d=1+d|0}a=c^b;a=m(-2048144789,a^(a>>>16|0));a=m(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function H(){this.ha=null}H.prototype=new z;H.prototype.constructor=H;H.prototype.b=function(){Ya=this;this.ha=k.Object.prototype.hasOwnProperty;return this};
H.prototype.$classData=x({La:0},"scala.scalajs.js.WrappedDictionary$Cache$",{La:1,a:1});var Ya=void 0;function I(){this.j=!1;this.Y=this.H=this.u=null;this.M=!1;this.aa=this.Z=0}I.prototype=new z;I.prototype.constructor=I;
I.prototype.b=function(){Za=this;this.u=(this.j=!!(k.ArrayBuffer&&k.Int32Array&&k.Float32Array&&k.Float64Array))?new k.ArrayBuffer(8):null;this.H=this.j?new k.Int32Array(this.u,0,2):null;this.j&&new k.Float32Array(this.u,0,2);this.Y=this.j?new k.Float64Array(this.u,0,1):null;if(this.j)this.H[0]=16909060,a=1===((new k.Int8Array(this.u,0,8))[0]|0);else var a=!0;this.Z=(this.M=a)?0:1;this.aa=this.M?1:0;return this};
function va(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.j)a.Y[0]=b,a=$a(a.H[a.aa]|0,a.H[a.Z]|0);else{if(b!==b)a=!1,b=2047,c=+k.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+k.Math.pow(2,-1022)){b=+k.Math.pow(2,52);var c=+k.Math.log(d)/.6931471805599453,c=+k.Math.floor(c)|0,c=1023>c?c:1023,f=+k.Math.pow(2,c);f>d&&(c=-1+c|0,f/=2);f=d/f*b;d=+k.Math.floor(f);f-=d;d=.5>f?d:.5<f?1+d:0!==d%2?1+d:d;2<=d/
b&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+k.Math.pow(2,-1074),c=+k.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=$a(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.p^a.m}I.prototype.$classData=x({Na:0},"scala.scalajs.runtime.Bits$",{Na:1,a:1});var Za=void 0;function wa(){Za||(Za=(new I).b());return Za}function J(){}J.prototype=new z;J.prototype.constructor=J;J.prototype.b=function(){return this};
function r(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+m(65535&(b.charCodeAt(d)|0),c)|0,c=m(31,c),d=-1+d|0;return a}J.prototype.$classData=x({Pa:0},"scala.scalajs.runtime.RuntimeString$",{Pa:1,a:1});var ab=void 0;function t(){ab||(ab=(new J).b());return ab}function K(){}K.prototype=new z;K.prototype.constructor=K;K.prototype.b=function(){return this};function bb(a,b){return b&&b.$classData&&b.$classData.e.I?b:(new L).i(b)}
K.prototype.$classData=x({Qa:0},"scala.scalajs.runtime.package$",{Qa:1,a:1});var cb=void 0;function db(){cb||(cb=(new K).b());return cb}function G(){}G.prototype=new z;G.prototype.constructor=G;G.prototype.b=function(){return this};
function Xa(a){if(null===a)return 0;if("number"===typeof a){a=+a;var b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{var b=y(),c;if(-9223372036854775808>a)b.L=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.L=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.L=0>a&&0!==c?-1+d|0:d}b=b.L;y();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:va(wa(),a)}return a}return sa(a)?(a=null===a?y().B:a,b=$a(a.p,a.m),a=b.p,b=b.m,b===a>>31?a:a^
b):ua(a)}G.prototype.$classData=x({Sa:0},"scala.runtime.Statics$",{Sa:1,a:1});var Wa=void 0;function eb(){}eb.prototype=new z;eb.prototype.constructor=eb;function fb(){}fb.prototype=eb.prototype;function M(){this.h=null}M.prototype=new z;M.prototype.constructor=M;function gb(){}gb.prototype=M.prototype;
M.prototype.X=function(){if(void 0===k.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=bb(db(),b),null!==a)if(a&&a.$classData&&a.$classData.e.R)a=a.l;else throw db(),a&&a.$classData&&a.$classData.e.R?a.l:a;else throw b;}this.stackdata=a}else k.Error.captureStackTrace(this),this.stackdata=this;return this};M.prototype.O=function(){return this.h};M.prototype.k=function(){var a=ha(this).f.name,b=this.O();return null===b?a:a+": "+b};M.prototype.G=function(a,b,c,d){this.h=a;d&&this.X();return this};
function F(){}F.prototype=new Sa;F.prototype.constructor=F;F.prototype.b=function(){Ua=this;r(t(),"Seq");r(t(),"Map");r(t(),"Set");return this};F.prototype.$classData=x({Ka:0},"scala.util.hashing.MurmurHash3$",{Ka:1,bb:1,a:1});var Ua=void 0,ra=x({Ra:0},"scala.runtime.BoxedUnit",{Ra:1,a:1,c:1},void 0,void 0,function(a){return void 0===a}),qa=x({sa:0},"java.lang.Boolean",{sa:1,a:1,c:1,g:1},void 0,void 0,function(a){return"boolean"===typeof a});function hb(){this.h=null}hb.prototype=new gb;
hb.prototype.constructor=hb;function ib(){}ib.prototype=hb.prototype;function N(){this.A=null}N.prototype=new Qa;N.prototype.constructor=N;N.prototype.b=function(){jb=this;this.A=(new E).i(Oa().ca);(new E).i(Oa().W);(new E).i(null);return this};N.prototype.$classData=x({Fa:0},"scala.Console$",{Fa:1,Za:1,a:1,ab:1});var jb=void 0;function kb(){jb||(jb=(new N).b());return jb}function O(){this.L=0;this.B=null}O.prototype=new z;O.prototype.constructor=O;
O.prototype.b=function(){lb=this;this.B=$a(0,0);return this};
function mb(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ba(1E9)|0)-(0!==b?ba(b):32+ba(a)|0)|0,d=c,f=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,h=a,n=b;for(a=b=0;0<=c&&0!==(-2097152&n);){var l=h,v=n,xb=f,Va=d;if(v===Va?(-2147483648^l)>=(-2147483648^xb):(-2147483648^v)>=(-2147483648^Va))l=n,v=d,n=h-f|0,l=(-2147483648^n)>(-2147483648^h)?-1+(l-v|0)|0:l-v|0,h=n,n=l,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;l=d>>>1|0;f=f>>>1|0|d<<31;d=l}c=n;if(0===c?-1147483648<=(-2147483648^
h):-2147483648<=(-2147483648^c))c=4294967296*n+ +(h>>>0),h=c/1E9,f=h/4294967296|0,d=b,b=h=d+(h|0)|0,a=(-2147483648^h)<(-2147483648^d)?1+(a+f|0)|0:a+f|0,h=c%1E9|0;c=""+h;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}O.prototype.$classData=x({Oa:0},"scala.scalajs.runtime.RuntimeLong$",{Oa:1,a:1,ga:1,c:1});var lb=void 0;function y(){lb||(lb=(new O).b());return lb}function nb(){}nb.prototype=new z;nb.prototype.constructor=nb;function ob(){}ob.prototype=nb.prototype;
var ia=x({na:0},"java.lang.String",{na:1,a:1,c:1,Xa:1,g:1},void 0,void 0,function(a){return"string"===typeof a}),ka=x({ta:0},"java.lang.Byte",{ta:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return ja(a)}),pa=x({va:0},"java.lang.Double",{va:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),oa=x({wa:0},"java.lang.Float",{wa:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),na=x({ya:0},"java.lang.Integer",{ya:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return"number"===
typeof a&&(a|0)===a&&1/a!==1/-0}),ta=x({Ba:0},"java.lang.Long",{Ba:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return sa(a)});function pb(){this.h=null}pb.prototype=new ib;pb.prototype.constructor=pb;function P(){}P.prototype=pb.prototype;var ma=x({Ca:0},"java.lang.Short",{Ca:1,o:1,a:1,c:1,g:1},void 0,void 0,function(a){return la(a)});function Q(){this.J=this.V=null;this.n=0}Q.prototype=new z;Q.prototype.constructor=Q;function qb(a){var b=new Q;b.V=a;b.J=k.Object.keys(a);b.n=0;return b}
Q.prototype.k=function(){return"\x3citerator\x3e"};function rb(a){var b=a.J[a.n];a.n=1+a.n|0;a=a.V;Ya||(Ya=(new H).b());if(Ya.ha.call(a,b))a=a[b];else throw(new R).F("key not found: "+b);var c=new S;c.r=b;c.s=a;return c}Q.prototype.$classData=x({Ma:0},"scala.scalajs.js.WrappedDictionary$DictionaryIterator",{Ma:1,a:1,db:1,eb:1,cb:1});function T(){this.m=this.p=0}T.prototype=new fb;T.prototype.constructor=T;
T.prototype.k=function(){y();var a=this.p,b=this.m;return b===a>>31?""+a:0>b?"-"+mb(-a|0,0!==a?~b:-b|0):mb(a,b)};function $a(a,b){var c=new T;c.p=a;c.m=b;return c}T.prototype.y=function(){return this.p^this.m};function sa(a){return!!(a&&a.$classData&&a.$classData.e.ia)}T.prototype.$classData=x({ia:0},"scala.scalajs.runtime.RuntimeLong",{ia:1,o:1,a:1,c:1,g:1});function U(){}U.prototype=new ob;U.prototype.constructor=U;function sb(){}sb.prototype=U.prototype;U.prototype.pa=function(){return this};
function V(){this.h=null}V.prototype=new P;V.prototype.constructor=V;V.prototype.F=function(a){M.prototype.G.call(this,a,0,0,!0);return this};V.prototype.$classData=x({xa:0},"java.lang.IndexOutOfBoundsException",{xa:1,Q:1,P:1,I:1,a:1,c:1});function W(){}W.prototype=new ob;W.prototype.constructor=W;W.prototype.b=function(){return this};W.prototype.$classData=x({Aa:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{Aa:1,ma:1,a:1,ka:1,ra:1,la:1});function R(){this.h=null}R.prototype=new P;
R.prototype.constructor=R;R.prototype.F=function(a){M.prototype.G.call(this,a,0,0,!0);return this};R.prototype.$classData=x({Ea:0},"java.util.NoSuchElementException",{Ea:1,Q:1,P:1,I:1,a:1,c:1});function X(){this.z=this.ba=this.h=null;this.N=!1}X.prototype=new P;X.prototype.constructor=X;
X.prototype.O=function(){if(!this.N&&!this.N){var a;if(null===this.z)a="null";else try{a=ga(this.z)+" ("+("of class "+ha(this.z).f.name)+")"}catch(b){if(null!==bb(db(),b))a="an instance of class "+ha(this.z).f.name;else throw b;}this.ba=a;this.N=!0}return this.ba};X.prototype.i=function(a){this.z=a;M.prototype.G.call(this,null,0,0,!0);return this};X.prototype.$classData=x({Ha:0},"scala.MatchError",{Ha:1,Q:1,P:1,I:1,a:1,c:1});function S(){this.s=this.r=null}S.prototype=new z;
S.prototype.constructor=S;e=S.prototype;e.fa=function(){return"Tuple2"};e.da=function(){return 2};e.ea=function(a){a:switch(a){case 0:a=this.r;break a;case 1:a=this.s;break a;default:throw(new V).F(""+a);}return a};e.k=function(){return"("+this.r+","+this.s+")"};e.y=function(){return Ta(this)};e.$classData=x({oa:0},"scala.Tuple2",{oa:1,a:1,$a:1,Ia:1,Ga:1,ga:1,c:1});function Y(){}Y.prototype=new sb;Y.prototype.constructor=Y;function tb(){}tb.prototype=Y.prototype;
Y.prototype.qa=function(){U.prototype.pa.call(this);return this};function Z(){this.w=this.$=null}Z.prototype=new tb;Z.prototype.constructor=Z;function Na(a){var b=new Z;b.$=a;(new W).b();Y.prototype.qa.call(b);b.w="";return b}function ub(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.w=""+a.w+b,b="";else{var d=""+a.w+b.substring(0,c);k.console&&(a.$&&k.console.error?k.console.error(d):k.console.log(d));a.w="";b=b.substring(1+c|0)}}}
Z.prototype.$classData=x({za:0},"java.lang.JSConsoleBasedPrintStream",{za:1,Ua:1,Ta:1,ma:1,a:1,ka:1,ra:1,la:1,Wa:1});function L(){this.l=this.h=null}L.prototype=new P;L.prototype.constructor=L;e=L.prototype;e.fa=function(){return"JavaScriptException"};e.da=function(){return 1};e.X=function(){this.stackdata=this.l;return this};e.ea=function(a){switch(a){case 0:return this.l;default:throw(new V).F(""+a);}};e.O=function(){return ga(this.l)};
e.i=function(a){this.l=a;M.prototype.G.call(this,null,0,0,!0);return this};e.y=function(){return Ta(this)};e.$classData=x({R:0},"scala.scalajs.js.JavaScriptException",{R:1,Q:1,P:1,I:1,a:1,c:1,Ia:1,Ga:1,ga:1});La||(La=(new C).b());ub(kb().A.q,"Hello world from Scala.js! dd\n");ub(kb().A.q,"----\n");ub(kb().A.q,"To demonstrate usage of Node.js api, here's some of your environment:\n");for(var vb={},wb=0,yb=qb(k.process.env);5>wb&&yb.n<(yb.J.length|0);){var zb=rb(yb);vb[zb.r]=zb.s;wb=1+wb|0}
for(var Ab=qb(vb);Ab.n<(Ab.J.length|0);){var Bb=rb(Ab);if(null!==Bb){var Cb=Bb.r+" \x3d "+Bb.s;ub(kb().A.q,Cb+"\n")}else throw(new X).i(Bb);};
//# sourceMappingURL=scalajs-cli-demo-opt.js.map
